#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo "📦 package-lock.json changed. Run `npm install` to bring your dependencies up to date."
fi

if changed 'pnpm-lock.yaml'; then
  echo "📦 pnpm-lock.yaml changed. Running `pnpm install` to bring your dependencies up to date..."
  pnpm install
fi
